// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ispjuxtvrxykioorhbmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcGp1eHR2cnh5a2lvb3JoYm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4MTAzNDAsImV4cCI6MjA4NTM4NjM0MH0.Vfr2kuXTfQVBBzx7ayEYGOoAxeuZ1vblgQajvjhHFSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});